// src/lib/components/shared/layout/Drawer.svelte
<script lang="ts">
  export let name: string;
</script>

<div class="drawer drawer-end">
  <input id={name} type="checkbox" class="drawer-toggle cursor-default" />
  <div class="drawer-content max-h-screen overscroll-y-none">
    <slot name="main" />
  </div>
  <div class="drawer-side z-20">
    <label for={name} class="drawer-overlay cursor-default" />
    <slot name="drawer" />
  </div>
</div>

// src/components/shared/layout/Drawer.vue
<script setup lang="ts">
defineProps({ name: { type: String, required: true }, title: { type: String, required: true } })
</script>

<template>
    <div class="drawer drawer-end">
        <input :id="name" type="checkbox" class="drawer-toggle cursor-default" />
        <div class="drawer-content max-h-screen overscroll-y-none">
            <slot :name="name" />
        </div>
        <div class="drawer-side z-20">
            <label :for="name" class="drawer-overlay cursor-default" />
            <slot name="drawer-content" />
        </div>
    </div>
</template>
