// src/lib/components/window/Main.svelte
<script>
  import Drawer from '$lib/components/shared/layout/Drawer.svelte';
  import Nav from './Nav.svelte';
  import Queue from './Queue.svelte';
</script>

<Drawer name="main">
  <div slot="main">
    <Nav />
    <main class="flex h-fit pt-2">
      <div class="flex h-full w-full">
        <slot />
      </div>
    </main>
  </div>
  <div slot="drawer">
    <Queue />
  </div>
</Drawer>

// src/components/window/Main.vue
<script setup lang="ts">
import Nav from './Nav.vue';
import Drawer from "../shared/layout/Drawer.vue"
import Settings from "./Settings.vue"
</script>

<template>
    <Drawer name="main" title="Main">
        <template v-slot:main>
            <main>
                <Nav />
                <div class="flex">
                </div>
            </main>
        </template>
        <template v-slot:drawer-content>
            <Settings />
        </template>
    </Drawer>
</template>
